server:
  port: 8087
spring:
    devtools:
      restart:
        exclude:  static/**,public/**
        enabled:  true
    application:
      name: redis-manage
    redis:
      host: 116.62.187.190
      password:
