server:
  port: 8087
spring:
    devtools:
      restart:
        exclude:  static/**,public/**
        enabled:  true
    application:
      name: springboot-webSocket
manager:
  username: admin
  password: admin